### PR TITLE
xsimd to 11.0.0

### PR DESCRIPTION
**Pull request by cbouss**
Update to 11.0.0

https://github.com/xtensor-stack/xsimd

### CODE REVIEW

**Review by SC426 — APPROVED** [review]

**Review by ryanskeith — COMMENTED** [review]
This looks good.

I noticed there is a 11.1.0 version out. https://github.com/xtensor-stack/xsimd/releases/tag/11.1.0.

But perhaps what you need is an exact version.

**Comment by skupr-anaconda** [comment]
> This looks good.
> 
> I noticed there is a 11.1.0 version out. https://github.com/xtensor-stack/xsimd/releases/tag/11.1.0.
> 
> But perhaps what you need is an exact version.

Yeah, looks like pythran relies on xsimd 11.0.0 https://github.com/serge-sans-paille/pythran/pull/2103 and see https://metayaml-conda.fly.dev/metayaml/reverse_dependencies?name=xsimd

**Comment by cbouss** [comment]
Indeed pythran requires 11.0.0. I added a patch from upstream that pythran also uses, for C++11 compatibility.

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Pull request merged**
